src/objects/XC_Line_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Footer_Image_URL__c</fullName>
        <label>Footer Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Footer_Text__c</fullName>
        <label>Footer Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Header_Image_URL__c</fullName>
        <label>Header Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Header_Text__c</fullName>
        <label>Header Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Line_Sheet_Text__c</fullName>
        <label>Line Sheet Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>XC_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Line Sheets</relationshipLabel>
        <relationshipName>Line_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>XC_Template__c</fullName>
        <label>Template</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Template One</fullName>
                </value>
                <value>
                    <fullName>Template Two</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Line Sheet</label>
    <nameField>
        <displayFormat>LSN-{0000}</displayFormat>
        <label>Line Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/XC_Line_Sheet_Item__c.object
<CustomObject>
    <fields>
        <fullName>XC_Line_Sheet__c</fullName>
        <label>Line Sheet</label>
        <referenceTo>XC_Line_Sheet__c</referenceTo>
        <relationshipLabel>Line Sheet Items</relationshipLabel>
        <relationshipName>Line_Sheet_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>XC_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Line Sheet Items</relationshipLabel>
        <relationshipName>Line_Sheet_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>XC_Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Line Sheet Item</label>
    <nameField>
        <displayFormat>LSIN-{0000}</displayFormat>
        <label>Line Sheet Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Sheet Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/XC_LWC_LineSheetWrappers.cls
/*
 * @FileName: XC_LWC_LineSheetWrappers
 * @Description:
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       9/21/2020         Created
 *-----------------------------------------------------------  
 */
public inherited sharing class XC_LWC_LineSheetWrappers {

    public class LineSheetWrapper {
        public String id;
        public String name;
        public String template;
        public String contactId;
        public String contactName;
        public String headerImageUrl;
        public String headerText;
        public String lineSheetText;
        public String footerImageUrl;
        public String footerText;
        public List<LineSheetItemWrapper> lineSheetItems;

        public LineSheetWrapper() {}

        public LineSheetWrapper(XC_Line_Sheet__c lineSheet) {
            this.id = lineSheet.Id;
            this.name = lineSheet.Name;
            this.template = lineSheet.XC_Template__c;
            this.contactId = lineSheet.XC_Contact__c;
            this.contactName = lineSheet.XC_Contact__r.Name;
            this.headerImageUrl = lineSheet.Header_Image_URL__c;
            this.headerText = lineSheet.Header_Text__c;
            this.lineSheetText = lineSheet.Line_Sheet_Text__c;
            this.footerImageUrl = lineSheet.Footer_Image_URL__c;
            this.footerText = lineSheet.Footer_Text__c;
        }
    }

    public class LineSheetItemWrapper {
        public String id;
        public Integer sortOrder;
        public String productId;
        public String productName;
        public String sku;
        public String imgURL;
        public String altText;

        public LineSheetItemWrapper(XC_Line_Sheet_Item__c item, XC_LWC_ProductWrappers.ProductDetails productWrapper) {
            Map<String,Object> fields = (Map<String,Object>) productWrapper.productDetail.fields;
            ConnectApi.ProductMedia imageDetails = productWrapper.productDetail.defaultImage;

            this.id = item.Id;
            this.sortOrder = Integer.valueOf(item.XC_Sort_Order__c);
            this.productId = item.XC_Product__c;
            this.productName = (String) fields.get('Name');
            this.sku = (String) fields.get('StockKeepingUnit');
            this.imgURL = imageDetails.url;
            this.altText = imageDetails.alternateText;
        }
    }
}